version: "3"

services:
  website-app:
    container_name: website-app
    build:
      dockerfile: Dockerfile
      args:
        JWT_SECRET: ${JWT_SECRET}
        DISCORD_CLIENT_ID: ${DISCORD_CLIENT_ID}
        DISCORD_CLIENT_SECRET: ${DISCORD_CLIENT_SECRET}
        DISCORD_REDIRECT_URI: ${DISCORD_REDIRECT_URI}
        DISCORD_TOKEN_URL: ${DISCORD_TOKEN_URL}
        DISCORD_AUTHORIZE_URL: ${DISCORD_AUTHORIZE_URL}
        REDIS_URL: ${REDIS_URL}
        REDIS_TOKEN: ${REDIS_TOKEN}
        STRIPE_SECRET_KEY: ${STRIPE_SECRET_KEY}
        STRIPE_WEBHOOK_SECRET: ${STRIPE_WEBHOOK_SECRET}
        NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY: ${NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY}
        NEXT_PUBLIC_PREMIUM_MONTHLY_PRICE_ID: ${NEXT_PUBLIC_PREMIUM_MONTHLY_PRICE_ID}
        NEXT_PUBLIC_PREMIUM_YEARLY_PRICE_ID: ${NEXT_PUBLIC_PREMIUM_YEARLY_PRICE_ID}
        MONGODB_URI: ${MONGODB_URI}
        UPSTASH_API_KEY: ${UPSTASH_API_KEY}
    restart: always
    ports:
      - 2123:2123



